// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmrt1TEy7Ju50CX53lK2Ag1kwVt455Qwg',
    appId: '1:855340148094:web:1f18f302894f8df942bf2f',
    messagingSenderId: '855340148094',
    projectId: 'cashswap-3fbdc',
    authDomain: 'cashswap-3fbdc.firebaseapp.com',
    storageBucket: 'cashswap-3fbdc.firebasestorage.app',
    measurementId: 'G-GER8X5GYQM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjew_uDh7dmYgrKaQXfxl1WWjK3-clPN4',
    appId: '1:855340148094:android:572a1a04778f1ec342bf2f',
    messagingSenderId: '855340148094',
    projectId: 'cashswap-3fbdc',
    storageBucket: 'cashswap-3fbdc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwkmmdINi0LU2DgnAlAjvns4-Y5sYfjnc',
    appId: '1:855340148094:ios:98773bcd0cf9d4f942bf2f',
    messagingSenderId: '855340148094',
    projectId: 'cashswap-3fbdc',
    storageBucket: 'cashswap-3fbdc.firebasestorage.app',
    iosBundleId: 'com.example.cashswapApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwkmmdINi0LU2DgnAlAjvns4-Y5sYfjnc',
    appId: '1:855340148094:ios:98773bcd0cf9d4f942bf2f',
    messagingSenderId: '855340148094',
    projectId: 'cashswap-3fbdc',
    storageBucket: 'cashswap-3fbdc.firebasestorage.app',
    iosBundleId: 'com.example.cashswapApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmrt1TEy7Ju50CX53lK2Ag1kwVt455Qwg',
    appId: '1:855340148094:web:ee76a71103e302b042bf2f',
    messagingSenderId: '855340148094',
    projectId: 'cashswap-3fbdc',
    authDomain: 'cashswap-3fbdc.firebaseapp.com',
    storageBucket: 'cashswap-3fbdc.firebasestorage.app',
    measurementId: 'G-CJF5DBET9C',
  );
}
